# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gmaynadi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/15 17:14:21 by gmaynadi          #+#    #+#              #
#    Updated: 2018/11/15 17:26:42 by gmaynadi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FLAGS = -Wall -Werror -Wextra -o

all: $(NAME)

$(NAME):
	@gcc $(FLAGS) $(NAME) $(NAME).c

clean:
	@rm -f $(NAME)

fclean: clean

re: fclean all
